# Generated by Django 5.0.4 on 2024-04-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('cat', models.CharField(choices=[('HL', 'Хилы'), ('DD', 'ДД'), ('TR', 'Торговцы'), ('GD', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('FG', 'Кузнецы'), ('LT', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний')], default='None', max_length=10)),
                ('text', models.TextField(default='Текст поста', max_length=1000)),
                ('content', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Текст комментария')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
